language: go

go:
  - '1.9'

sudo: required
services: docker

script:
  - GOARCH=amd64 GOOS=linux go build -o bin/pipeline-blog-linux-amd64 main.go
  - docker build -t $TRAVIS_REPO_SLUG .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag $TRAVIS_REPO_SLUG $TRAVIS_REPO_SLUG:dev;
    docker push $TRAVIS_REPO_SLUG:dev;
    fi
  - if [ $TRAVIS_TAG ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $TRAVIS_REPO_SLUG;
    docker tag $TRAVIS_REPO_SLUG $TRAVIS_REPO_SLUG:$TRAVIS_TAG;
    docker push $TRAVIS_REPO_SLUG:$TRAVIS_TAG;
    fi
